name: Deploy dev to Fly

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-dev-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a cerevana-dev --config fly.dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}
